FROM eclipse-temurin:21-jre

WORKDIR /app

COPY build/libs/auth-service-1.0.0.jar app.jar

ENV JAVA_OPTS="-Xms512m -Xmx1024m --enable-preview"

EXPOSE 8080 9080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
