# Docker Compose for TradeMaster Frontend
# Clean setup for React frontend with development and production modes
version: '3.8'

services:
  # React Frontend Development Server
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
      - "5173:5173"  # Vite dev server
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:8083
      - VITE_EVENT_BUS_URL=http://localhost:8081
      - VITE_WS_URL=ws://localhost:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend-network
    restart: unless-stopped
    profiles:
      - dev

  # React Frontend Production Build with Nginx
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8083
      - VITE_EVENT_BUS_URL=http://localhost:8081
      - VITE_WS_URL=ws://localhost:8081
    networks:
      - frontend-network
    restart: unless-stopped
    profiles:
      - prod

volumes:
  frontend_node_modules:
    driver: local

networks:
  frontend-network:
    driver: bridge