# Alertmanager Configuration for TradeMaster Trading Service
# Integrates with PagerDuty and Slack for alert notifications
# @version 1.0.0

global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

# Alert routing tree
route:
  receiver: 'default'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  
  routes:
    # Critical alerts - PagerDuty + Slack
    - match:
        severity: critical
      receiver: 'pagerduty-critical'
      continue: true
      routes:
        - match:
            component: application
          receiver: 'slack-critical-app'
        - match:
            component: database
          receiver: 'slack-critical-db'
        - match:
            component: trading
          receiver: 'slack-critical-trading'

    # Warning alerts - Slack only
    - match:
        severity: warning
      receiver: 'slack-warnings'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

    # Info alerts - Slack only
    - match:
        severity: info
      receiver: 'slack-info'
      group_wait: 1m
      group_interval: 10m
      repeat_interval: 24h

# Alert receivers
receivers:
  # Default receiver (fallback)
  - name: 'default'
    slack_configs:
      - channel: '#trademaster-alerts'
        title: 'TradeMaster Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # PagerDuty for critical alerts
  - name: 'pagerduty-critical'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        severity: 'critical'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
        details:
          firing: '{{ .Alerts.Firing | len }}'
          resolved: '{{ .Alerts.Resolved | len }}'
          alertname: '{{ .GroupLabels.alertname }}'
          cluster: '{{ .GroupLabels.cluster }}'
          component: '{{ .GroupLabels.component }}'
        client: 'TradeMaster Prometheus'
        client_url: '{{ .ExternalURL }}'

  # Slack for critical application alerts
  - name: 'slack-critical-app'
    slack_configs:
      - channel: '#trademaster-critical'
        username: 'TradeMaster Alerts'
        icon_emoji: ':rotating_light:'
        title: ':fire: CRITICAL: Application Issue'
        title_link: '{{ .ExternalURL }}'
        text: |-
          *Alert*: {{ .GroupLabels.alertname }}
          *Summary*: {{ .CommonAnnotations.summary }}
          *Description*: {{ .CommonAnnotations.description }}
          *Runbook*: {{ .CommonAnnotations.runbook_url }}
          *Dashboard*: {{ .CommonAnnotations.dashboard }}
          
          *Status*: {{ .Status }}
          *Severity*: {{ .CommonLabels.severity }}
          *Component*: {{ .CommonLabels.component }}
          *Instance*: {{ .CommonLabels.instance }}
        color: 'danger'
        send_resolved: true

  # Slack for critical database alerts
  - name: 'slack-critical-db'
    slack_configs:
      - channel: '#trademaster-database'
        username: 'TradeMaster DB Alerts'
        icon_emoji: ':database:'
        title: ':fire: CRITICAL: Database Issue'
        text: '{{ .CommonAnnotations.summary }}'
        color: 'danger'
        send_resolved: true

  # Slack for critical trading alerts
  - name: 'slack-critical-trading'
    slack_configs:
      - channel: '#trademaster-trading'
        username: 'TradeMaster Trading Alerts'
        icon_emoji: ':chart_with_upwards_trend:'
        title: ':fire: CRITICAL: Trading Issue'
        text: '{{ .CommonAnnotations.summary }}'
        color: 'danger'
        send_resolved: true

  # Slack for warning alerts
  - name: 'slack-warnings'
    slack_configs:
      - channel: '#trademaster-warnings'
        username: 'TradeMaster Alerts'
        icon_emoji: ':warning:'
        title: ':warning: Warning: {{ .GroupLabels.alertname }}'
        text: |-
          *Summary*: {{ .CommonAnnotations.summary }}
          *Description*: {{ .CommonAnnotations.description }}
          *Runbook*: {{ .CommonAnnotations.runbook_url }}
        color: 'warning'
        send_resolved: true

  # Slack for info alerts
  - name: 'slack-info'
    slack_configs:
      - channel: '#trademaster-info'
        username: 'TradeMaster Info'
        icon_emoji: ':information_source:'
        title: 'Info: {{ .GroupLabels.alertname }}'
        text: '{{ .CommonAnnotations.summary }}'
        color: 'good'
        send_resolved: true

# Inhibition rules (suppress redundant alerts)
inhibit_rules:
  # Suppress warnings when critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Suppress info alerts when warning is firing
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'instance']

  # Suppress component alerts when application is down
  - source_match:
      alertname: 'ApplicationDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance']
