global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TradeMaster Auth Service
  - job_name: 'trademaster-auth'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Kong API Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL (using postgres_exporter if added later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis (using redis_exporter if added later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

# Alertmanager configuration (if needed later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093