# TradeMaster Alert Rules for Prometheus
groups:
  - name: trademaster.critical
    rules:
      # Service Health Alerts
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
          category: availability
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 30 seconds"

      - alert: HighErrorRate
        expr: (rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])) > 0.1
        for: 2m
        labels:
          severity: critical
          category: reliability
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is {{ $value | humanizePercentage }} for service {{ $labels.job }}"

      # Trading System Critical Alerts
      - alert: TradingServiceCritical
        expr: up{job="trading-service"} == 0
        for: 15s
        labels:
          severity: critical
          category: trading
        annotations:
          summary: "Trading service is DOWN - CRITICAL"
          description: "Trading service is down - immediate action required"

      - alert: OrderExecutionFailure
        expr: rate(trading_order_failed_total[5m]) > 0.05
        for: 1m
        labels:
          severity: critical
          category: trading
        annotations:
          summary: "High order execution failure rate"
          description: "Order execution failure rate is {{ $value }} orders/sec"

      - alert: PortfolioCalculationFailure
        expr: rate(portfolio_calculation_errors_total[5m]) > 0.01
        for: 2m
        labels:
          severity: critical
          category: portfolio
        annotations:
          summary: "Portfolio calculation failures detected"
          description: "Portfolio calculation error rate is {{ $value }} errors/sec"

  - name: trademaster.performance
    rules:
      # Response Time Alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1.0
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "High response time for {{ $labels.job }}"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.job }}"

      - alert: TradingLatencyHigh
        expr: histogram_quantile(0.95, rate(trading_order_processing_duration_seconds_bucket[5m])) > 0.1
        for: 2m
        labels:
          severity: warning
          category: trading
        annotations:
          summary: "High trading latency detected"
          description: "95th percentile trading latency is {{ $value }}s (threshold: 100ms)"

      # Resource Usage Alerts
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 1000
        for: 5m
        labels:
          severity: warning
          category: resources
        annotations:
          summary: "High memory usage on {{ $labels.job }}"
          description: "Memory usage is {{ $value }}MB for service {{ $labels.job }}"

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          category: resources
        annotations:
          summary: "High CPU usage on {{ $labels.job }}"
          description: "CPU usage is {{ $value | humanizePercentage }} for service {{ $labels.job }}"

  - name: trademaster.business
    rules:
      # Agent Orchestration Alerts
      - alert: AgentRegistrationFailure
        expr: rate(agent_registration_failed_total[5m]) > 0.01
        for: 2m
        labels:
          severity: warning
          category: agents
        annotations:
          summary: "Agent registration failures detected"
          description: "Agent registration failure rate is {{ $value }} failures/sec"

      - alert: TaskQueueBacklog
        expr: task_queue_size > 1000
        for: 5m
        labels:
          severity: warning
          category: agents
        annotations:
          summary: "High task queue backlog"
          description: "Task queue has {{ $value }} pending tasks"

      # Authentication & Authorization Alerts
      - alert: AuthenticationFailureRate
        expr: rate(authentication_failed_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value }} failures/sec"

      - alert: RateLimitExceeded
        expr: rate(rate_limit_exceeded_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Rate limit exceeded frequently"
          description: "Rate limit exceeded {{ $value }} times/sec"

  - name: trademaster.database
    rules:
      # Database Connection Alerts
      - alert: DatabaseConnectionPoolExhausted
        expr: hikaricp_connections_active >= hikaricp_connections_max
        for: 1m
        labels:
          severity: critical
          category: database
        annotations:
          summary: "Database connection pool exhausted"
          description: "All {{ $value }} database connections are in use"

      - alert: SlowDatabaseQueries
        expr: histogram_quantile(0.95, rate(spring_data_repository_invocations_seconds_bucket[5m])) > 1.0
        for: 3m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile query time is {{ $value }}s"

  - name: trademaster.infrastructure
    rules:
      # Redis Alerts
      - alert: RedisConnectionFailure
        expr: redis_connected_clients == 0
        for: 30s
        labels:
          severity: critical
          category: cache
        annotations:
          summary: "Redis connection failure"
          description: "No clients connected to Redis"

      - alert: RedisMemoryHigh
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) > 0.9
        for: 5m
        labels:
          severity: warning
          category: cache
        annotations:
          summary: "Redis memory usage high"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

      # Kong Gateway Alerts
      - alert: KongGatewayDown
        expr: up{job="kong-gateway"} == 0
        for: 30s
        labels:
          severity: critical
          category: gateway
        annotations:
          summary: "Kong Gateway is down"
          description: "Kong API Gateway is not responding"