# Prometheus configuration for TradeMaster
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'trademaster'
    region: 'local'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Applications
  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'user-profile-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'trading-engine'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Infrastructure Components
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Kafka JMX Metrics (if enabled)
  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9308']
    scrape_interval: 30s

  # Frontend Application (if metrics endpoint added)
  - job_name: 'trademaster-frontend'
    static_configs:
      - targets: ['host.docker.internal:5173']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Custom Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/api/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # API Gateway Metrics (if using)
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s