# Kong API Gateway Configuration for TradeMaster User Profile Service
# Version: 1.0.0
# Description: API Gateway setup with JWT authentication, rate limiting, and role-based access

_format_version: "3.0"
_transform: true

services:
  - name: trademaster-user-profile-service
    url: http://user-profile-service:8082
    protocol: http
    host: user-profile-service
    port: 8082
    path: /api/v1
    connect_timeout: 30000
    write_timeout: 30000
    read_timeout: 30000
    retries: 3
    
    # Routes configuration
    routes:
      # Health check endpoints (public)
      - name: user-profile-health
        paths:
          - /api/v1/profiles/actuator/health
          - /api/v1/profiles/actuator/info
        methods:
          - GET
          - OPTIONS
        strip_path: false
        preserve_host: false
        
        plugins:
          # Basic rate limiting for health checks
          - name: rate-limiting
            config:
              minute: 60
              hour: 1000
              policy: local
              fault_tolerant: true
              
          # CORS configuration
          - name: cors
            config:
              origins:
                - "http://localhost:3000"
                - "https://trademaster.com"
                - "https://*.trademaster.com"
              methods:
                - GET
                - OPTIONS
              headers:
                - Accept
                - Content-Type
              credentials: true
              max_age: 3600

      # User profile endpoints (requires authentication)
      - name: user-profile-authenticated
        paths:
          - /api/v1/profiles/me
          - /api/v1/documents/me
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        strip_path: false
        preserve_host: false
        
        plugins:
          # JWT Authentication
          - name: jwt
            config:
              uri_param_names:
                - jwt
              cookie_names:
                - jwt
              header_names:
                - authorization
              claims_to_verify:
                - exp
                - sub
              key_claim_name: iss
              secret_is_base64: false
              run_on_preflight: false
              
          # Rate limiting for authenticated users
          - name: rate-limiting
            config:
              minute: 500   # 500 requests per minute for user operations
              hour: 5000    # 5000 requests per hour
              day: 50000    # 50000 requests per day
              policy: local
              fault_tolerant: true
              hide_client_headers: false
              
          # Request size limiting (for file uploads)
          - name: request-size-limiting
            config:
              allowed_payload_size: 15  # 15MB max for document uploads
              
          # CORS configuration
          - name: cors
            config:
              origins:
                - "http://localhost:3000"
                - "https://trademaster.com"
                - "https://*.trademaster.com"
              methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-Type
                - Date
                - Authorization
                - X-Auth-Token
                - X-Request-ID
              exposed_headers:
                - X-Auth-Token
                - X-RateLimit-Limit
                - X-RateLimit-Remaining
              credentials: true
              max_age: 3600
              
          # Security headers
          - name: response-transformer
            config:
              add:
                headers:
                  - "X-Content-Type-Options:nosniff"
                  - "X-Frame-Options:DENY"
                  - "X-XSS-Protection:1; mode=block"
                  - "Strict-Transport-Security:max-age=31536000; includeSubDomains"

      # Admin endpoints (requires admin role)
      - name: user-profile-admin
        paths:
          - /api/v1/profiles/search
          - /api/v1/profiles/by-kyc-status
          - /api/v1/profiles/statistics
          - /api/v1/profiles/kyc-renewal-needed
          - /api/v1/documents/pending-verification
          - /api/v1/documents/user
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        strip_path: false
        preserve_host: false
        
        plugins:
          # JWT Authentication with admin role validation
          - name: jwt
            config:
              uri_param_names:
                - jwt
              cookie_names:
                - jwt
              header_names:
                - authorization
              claims_to_verify:
                - exp
                - sub
                - roles
              key_claim_name: iss
              secret_is_base64: false
              
          # Custom plugin for role-based access (would need custom implementation)
          # - name: rbac
          #   config:
          #     required_roles:
          #       - ADMIN
          #       - COMPLIANCE_OFFICER
              
          # Higher rate limits for admin operations
          - name: rate-limiting
            config:
              minute: 1000  # 1000 requests per minute for admin
              hour: 10000   # 10000 requests per hour
              day: 100000   # 100000 requests per day
              policy: local
              fault_tolerant: true
              
          # Request logging for admin actions
          - name: file-log
            config:
              path: /var/log/kong/admin-actions.log
              reopen: true
              
          # Security headers
          - name: response-transformer
            config:
              add:
                headers:
                  - "X-Content-Type-Options:nosniff"
                  - "X-Frame-Options:DENY"
                  - "X-XSS-Protection:1; mode=block"
                  - "Strict-Transport-Security:max-age=31536000; includeSubDomains"
                  - "Content-Security-Policy:default-src 'self'"

      # Compliance endpoints (requires compliance officer role)
      - name: user-profile-compliance
        paths:
          - /api/v1/kyc
          - /api/v1/documents/verify
          - /api/v1/documents/verification-history
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        strip_path: false
        preserve_host: false
        
        plugins:
          # JWT Authentication with compliance role validation
          - name: jwt
            config:
              uri_param_names:
                - jwt
              cookie_names:
                - jwt
              header_names:
                - authorization
              claims_to_verify:
                - exp
                - sub
                - roles
              key_claim_name: iss
              secret_is_base64: false
              
          # Rate limiting for compliance operations
          - name: rate-limiting
            config:
              minute: 200   # 200 requests per minute for compliance
              hour: 2000    # 2000 requests per hour
              day: 20000    # 20000 requests per day
              policy: local
              fault_tolerant: true
              
          # Audit logging for compliance actions
          - name: file-log
            config:
              path: /var/log/kong/compliance-actions.log
              reopen: true
              
          # Security headers
          - name: response-transformer
            config:
              add:
                headers:
                  - "X-Content-Type-Options:nosniff"
                  - "X-Frame-Options:DENY"
                  - "X-XSS-Protection:1; mode=block"
                  - "Strict-Transport-Security:max-age=31536000; includeSubDomains"
                  - "Content-Security-Policy:default-src 'self'"
                  - "X-Audit-Required:true"

# Global plugins for user profile service
plugins:
  # Request logging
  - name: file-log
    config:
      path: /var/log/kong/user-profile-access.log
      reopen: true
      
  # Prometheus metrics
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true
      
  # Request/Response transformation
  - name: request-transformer
    config:
      add:
        headers:
          - "X-Gateway-Version:1.0.0"
          - "X-Service:user-profile-service"
          - "X-Request-ID:$(uuid)"
      remove:
        headers:
          - "X-Internal-Token"

# Consumer configuration (shared with auth service)
consumers:
  - username: trademaster-frontend
    keyauth_credentials:
      - key: frontend-api-key-2024
    jwt_secrets:
      - key: trademaster-auth-service
        secret: your-256-bit-secret-key-here-change-in-production
        
  - username: trademaster-mobile
    keyauth_credentials:
      - key: mobile-api-key-2024
    jwt_secrets:
      - key: trademaster-auth-service
        secret: your-256-bit-secret-key-here-change-in-production

# Upstreams configuration for load balancing
upstreams:
  - name: user-profile-service-upstream
    algorithm: round-robin
    healthchecks:
      passive:
        unhealthy:
          http_statuses:
            - 429
            - 500
            - 502
            - 503
            - 504
          tcp_failures: 3
          timeouts: 3
          http_failures: 3
        healthy:
          http_statuses:
            - 200
            - 201
            - 202
            - 204
          successes: 3
      active:
        type: http
        timeout: 10
        concurrency: 5
        http_path: /api/v1/profiles/actuator/health
        https_verify_certificate: false
        healthy:
          interval: 30
          http_statuses:
            - 200
          successes: 3
        unhealthy:
          interval: 30
          http_statuses:
            - 429
            - 500
            - 502
            - 503
            - 504
          tcp_failures: 3
          timeouts: 3
          http_failures: 3
    targets:
      - target: user-profile-service:8082
        weight: 100